### ISSUE TITLE
Assemblies with different/wrong version is referenced

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.CS.Club.Core#1]
After importing nugget packages for ODATA there are references to Newtonsoft.Json with v7.

Now several unit tests fails as the wrong assembly version is referenced/loaded. Some time ago you told me you had the same error - maybe you can explain to me how you fixed this.

Here is an example of one of the failed tests:

```
Test Name:	AnonymousRegistration2Fails
Test FullName:	biz.dfch.CS.Club.Core.Server.Tests.ApplicationData.Members.MembersControllerTest.AnonymousRegistration2Fails
Test Source:	c:\Github\biz.dfch.CS.Club.Core\src\biz.dfch.CS.Club.Core.Server.Tests\ApplicationData\Members\MembersControllerTest.cs : line 185
Test Outcome:	Failed
Test Duration:	0:00:00.7059327

Result Message:	
Test method biz.dfch.CS.Club.Core.Server.Tests.ApplicationData.Members.MembersControllerTest.AnonymousRegistration2Fails threw exception: 
System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Result StackTrace:	
at biz.dfch.CS.Club.Core.Server.Utilities.Clickatell.ClickatellShortMessageProvider.SendMessage(IShortMessage message)
   at biz.dfch.CS.Club.Core.Server.ApplicationData.Members.MembersController.AnonymousRegistration2(Member entity) in C:\Github\biz.dfch.CS.Club.Core\src\biz.dfch.CS.Club.Core\biz.dfch.CS.Club.Core.Server\ApplicationData\Members\MembersController.cs:line 73
   at biz.dfch.CS.Club.Core.Server.Tests.ApplicationData.Members.MembersControllerTest.AnonymousRegistration2Fails() in c:\Github\biz.dfch.CS.Club.Core\src\biz.dfch.CS.Club.Core.Server.Tests\ApplicationData\Members\MembersControllerTest.cs:line 198
```

**Comment by dfch** [comment]
removed Newtonsoft package and re-installed v7.0.1 (had to restart VS to complete installation) and now it is working. Issue can be closed.
